[tool.poetry]
name = "qnm-npom"
version = "1.0"
description = "visualization tool for the quasi-normal modes of nanoparticle on mirror"
authors = ["Eoin Elliott"]

[tool.poetry.dependencies]
python = "^3.6"
streamlit = "^0.86.0"
plotly = "^5.2.1"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
